// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/bunker.proto

package bunker_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerCharacteristic_Gender int32

const (
	PlayerCharacteristic_GENDER_UNSPECIFIED PlayerCharacteristic_Gender = 0
	PlayerCharacteristic_GENDER_MALE        PlayerCharacteristic_Gender = 1
	PlayerCharacteristic_GENDER_FEMALE      PlayerCharacteristic_Gender = 2
)

// Enum value maps for PlayerCharacteristic_Gender.
var (
	PlayerCharacteristic_Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	PlayerCharacteristic_Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x PlayerCharacteristic_Gender) Enum() *PlayerCharacteristic_Gender {
	p := new(PlayerCharacteristic_Gender)
	*p = x
	return p
}

func (x PlayerCharacteristic_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerCharacteristic_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bunker_proto_enumTypes[0].Descriptor()
}

func (PlayerCharacteristic_Gender) Type() protoreflect.EnumType {
	return &file_api_bunker_proto_enumTypes[0]
}

func (x PlayerCharacteristic_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerCharacteristic_Gender.Descriptor instead.
func (PlayerCharacteristic_Gender) EnumDescriptor() ([]byte, []int) {
	return file_api_bunker_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerCharacteristic_Orientation int32

const (
	PlayerCharacteristic_ORIENTATION_UNSPECIFIED PlayerCharacteristic_Orientation = 0
	PlayerCharacteristic_ORIENTATION_STRAIGHT    PlayerCharacteristic_Orientation = 1
	PlayerCharacteristic_ORIENTATION_BI          PlayerCharacteristic_Orientation = 2
	PlayerCharacteristic_ORIENTATION_HOMO        PlayerCharacteristic_Orientation = 3
)

// Enum value maps for PlayerCharacteristic_Orientation.
var (
	PlayerCharacteristic_Orientation_name = map[int32]string{
		0: "ORIENTATION_UNSPECIFIED",
		1: "ORIENTATION_STRAIGHT",
		2: "ORIENTATION_BI",
		3: "ORIENTATION_HOMO",
	}
	PlayerCharacteristic_Orientation_value = map[string]int32{
		"ORIENTATION_UNSPECIFIED": 0,
		"ORIENTATION_STRAIGHT":    1,
		"ORIENTATION_BI":          2,
		"ORIENTATION_HOMO":        3,
	}
)

func (x PlayerCharacteristic_Orientation) Enum() *PlayerCharacteristic_Orientation {
	p := new(PlayerCharacteristic_Orientation)
	*p = x
	return p
}

func (x PlayerCharacteristic_Orientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerCharacteristic_Orientation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_bunker_proto_enumTypes[1].Descriptor()
}

func (PlayerCharacteristic_Orientation) Type() protoreflect.EnumType {
	return &file_api_bunker_proto_enumTypes[1]
}

func (x PlayerCharacteristic_Orientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerCharacteristic_Orientation.Descriptor instead.
func (PlayerCharacteristic_Orientation) EnumDescriptor() ([]byte, []int) {
	return file_api_bunker_proto_rawDescGZIP(), []int{0, 1}
}

type PlayerCharacteristic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*PlayerCharacteristic_Age
	//	*PlayerCharacteristic_Gender_
	//	*PlayerCharacteristic_Orientation_
	//	*PlayerCharacteristic_Backpack
	Value isPlayerCharacteristic_Value `protobuf_oneof:"value"`
}

func (x *PlayerCharacteristic) Reset() {
	*x = PlayerCharacteristic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bunker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCharacteristic) ProtoMessage() {}

func (x *PlayerCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_api_bunker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCharacteristic.ProtoReflect.Descriptor instead.
func (*PlayerCharacteristic) Descriptor() ([]byte, []int) {
	return file_api_bunker_proto_rawDescGZIP(), []int{0}
}

func (m *PlayerCharacteristic) GetValue() isPlayerCharacteristic_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *PlayerCharacteristic) GetAge() int32 {
	if x, ok := x.GetValue().(*PlayerCharacteristic_Age); ok {
		return x.Age
	}
	return 0
}

func (x *PlayerCharacteristic) GetGender() PlayerCharacteristic_Gender {
	if x, ok := x.GetValue().(*PlayerCharacteristic_Gender_); ok {
		return x.Gender
	}
	return PlayerCharacteristic_GENDER_UNSPECIFIED
}

func (x *PlayerCharacteristic) GetOrientation() PlayerCharacteristic_Orientation {
	if x, ok := x.GetValue().(*PlayerCharacteristic_Orientation_); ok {
		return x.Orientation
	}
	return PlayerCharacteristic_ORIENTATION_UNSPECIFIED
}

func (x *PlayerCharacteristic) GetBackpack() string {
	if x, ok := x.GetValue().(*PlayerCharacteristic_Backpack); ok {
		return x.Backpack
	}
	return ""
}

type isPlayerCharacteristic_Value interface {
	isPlayerCharacteristic_Value()
}

type PlayerCharacteristic_Age struct {
	Age int32 `protobuf:"varint,1,opt,name=age,proto3,oneof"`
}

type PlayerCharacteristic_Gender_ struct {
	Gender PlayerCharacteristic_Gender `protobuf:"varint,2,opt,name=gender,proto3,enum=PlayerCharacteristic_Gender,oneof"`
}

type PlayerCharacteristic_Orientation_ struct {
	Orientation PlayerCharacteristic_Orientation `protobuf:"varint,3,opt,name=orientation,proto3,enum=PlayerCharacteristic_Orientation,oneof"`
}

type PlayerCharacteristic_Backpack struct {
	Backpack string `protobuf:"bytes,4,opt,name=backpack,proto3,oneof"`
}

func (*PlayerCharacteristic_Age) isPlayerCharacteristic_Value() {}

func (*PlayerCharacteristic_Gender_) isPlayerCharacteristic_Value() {}

func (*PlayerCharacteristic_Orientation_) isPlayerCharacteristic_Value() {}

func (*PlayerCharacteristic_Backpack) isPlayerCharacteristic_Value() {}

type RevealPlayerCharacteristicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RevealPlayerCharacteristicRequest) Reset() {
	*x = RevealPlayerCharacteristicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bunker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealPlayerCharacteristicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealPlayerCharacteristicRequest) ProtoMessage() {}

func (x *RevealPlayerCharacteristicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bunker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealPlayerCharacteristicRequest.ProtoReflect.Descriptor instead.
func (*RevealPlayerCharacteristicRequest) Descriptor() ([]byte, []int) {
	return file_api_bunker_proto_rawDescGZIP(), []int{1}
}

func (x *RevealPlayerCharacteristicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RevealPlayerCharacteristicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characteristic *PlayerCharacteristic `protobuf:"bytes,1,opt,name=characteristic,proto3" json:"characteristic,omitempty"`
}

func (x *RevealPlayerCharacteristicResponse) Reset() {
	*x = RevealPlayerCharacteristicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bunker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealPlayerCharacteristicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealPlayerCharacteristicResponse) ProtoMessage() {}

func (x *RevealPlayerCharacteristicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bunker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealPlayerCharacteristicResponse.ProtoReflect.Descriptor instead.
func (*RevealPlayerCharacteristicResponse) Descriptor() ([]byte, []int) {
	return file_api_bunker_proto_rawDescGZIP(), []int{2}
}

func (x *RevealPlayerCharacteristicResponse) GetCharacteristic() *PlayerCharacteristic {
	if x != nil {
		return x.Characteristic
	}
	return nil
}

var File_api_bunker_proto protoreflect.FileDescriptor

var file_api_bunker_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x86, 0x03, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12,
	0x36, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x22, 0x44, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45,
	0x10, 0x02, 0x22, 0x6e, 0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x52, 0x41, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x52, 0x49, 0x45,
	0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x49, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10,
	0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x48, 0x4f, 0x4d, 0x4f,
	0x10, 0x03, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x21, 0x52,
	0x65, 0x76, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x63, 0x0a, 0x22, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x32, 0x7a, 0x0a, 0x11, 0x42, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x1a, 0x52, 0x65,
	0x76, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x22, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x61,
	0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x52,
	0x65, 0x76, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x75, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_bunker_proto_rawDescOnce sync.Once
	file_api_bunker_proto_rawDescData = file_api_bunker_proto_rawDesc
)

func file_api_bunker_proto_rawDescGZIP() []byte {
	file_api_bunker_proto_rawDescOnce.Do(func() {
		file_api_bunker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_bunker_proto_rawDescData)
	})
	return file_api_bunker_proto_rawDescData
}

var file_api_bunker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_bunker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_bunker_proto_goTypes = []interface{}{
	(PlayerCharacteristic_Gender)(0),           // 0: PlayerCharacteristic.Gender
	(PlayerCharacteristic_Orientation)(0),      // 1: PlayerCharacteristic.Orientation
	(*PlayerCharacteristic)(nil),               // 2: PlayerCharacteristic
	(*RevealPlayerCharacteristicRequest)(nil),  // 3: RevealPlayerCharacteristicRequest
	(*RevealPlayerCharacteristicResponse)(nil), // 4: RevealPlayerCharacteristicResponse
}
var file_api_bunker_proto_depIdxs = []int32{
	0, // 0: PlayerCharacteristic.gender:type_name -> PlayerCharacteristic.Gender
	1, // 1: PlayerCharacteristic.orientation:type_name -> PlayerCharacteristic.Orientation
	2, // 2: RevealPlayerCharacteristicResponse.characteristic:type_name -> PlayerCharacteristic
	3, // 3: BunkerGameService.RevealPlayerCharacteristic:input_type -> RevealPlayerCharacteristicRequest
	4, // 4: BunkerGameService.RevealPlayerCharacteristic:output_type -> RevealPlayerCharacteristicResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_bunker_proto_init() }
func file_api_bunker_proto_init() {
	if File_api_bunker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_bunker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerCharacteristic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bunker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealPlayerCharacteristicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bunker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealPlayerCharacteristicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_bunker_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PlayerCharacteristic_Age)(nil),
		(*PlayerCharacteristic_Gender_)(nil),
		(*PlayerCharacteristic_Orientation_)(nil),
		(*PlayerCharacteristic_Backpack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_bunker_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bunker_proto_goTypes,
		DependencyIndexes: file_api_bunker_proto_depIdxs,
		EnumInfos:         file_api_bunker_proto_enumTypes,
		MessageInfos:      file_api_bunker_proto_msgTypes,
	}.Build()
	File_api_bunker_proto = out.File
	file_api_bunker_proto_rawDesc = nil
	file_api_bunker_proto_goTypes = nil
	file_api_bunker_proto_depIdxs = nil
}
